create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete set null,
  user_email text,
  route text not null,
  bus_name text,
  depart_date text,
  depart_time text,
  arrive_time text,
  trip_type text,
  total_price numeric(10, 2) not null,
  adult_qty int not null default 0,
  child_qty int not null default 0,
  senior_qty int not null default 0,
  student_qty int not null default 0,
  pwd_qty int not null default 0,
  seat_numbers int[] default '{}',
  receipt_email text,
  status text not null default 'confirmed',
  cancelled_at timestamptz,
  refunded_at timestamptz,
  refund_amount numeric(10, 2),
  created_at timestamptz default now()
);
